- name: Install work related packages
  become: yes
  apt:
    state: latest
    name:
    - network-manager-openvpn
    - network-manager-openvpn-gnome

- name: Install msteams
  block: 
  - name: Verify if msteams Is Installed
    stat:
      path: "/usr/bin/teams"
    register: "msteams_installed"
  
  - name: Install msteams
    apt:
      deb: https://packages.microsoft.com/repos/ms-teams/pool/main/t/teams/teams_1.3.00.30857_amd64.deb
    become: yes
    when: not msteams_installed.stat.exists

- name: Install postman
  become: yes
  snap:
    name: postman

- name: Install Hashicorp Vault
  block: 
  - name: "Vault: add GPG key"
    apt_key:
      url: https://apt.releases.hashicorp.com/gpg
    become: yes

  - name: "Vault: add APT repository"
    apt_repository:
      repo: deb [arch=amd64] https://apt.releases.hashicorp.com {{ansible_distribution_release}} main
    become: yes

  - name: "Vault: install package"
    apt:
      name: 
      - vault
      state: latest
    become: yes
