- name: Install work related packages
  become: yes
  apt:
    state: latest
    name:
    - network-manager-openvpn
    - network-manager-openvpn-gnome

- name: Install Hashicorp Vault
  block: 
  - name: "Vault: add GPG key"
    apt_key:
      url: https://apt.releases.hashicorp.com/gpg
    become: yes

  - name: "Vault: add APT repository"
    apt_repository:
      repo: deb [arch=amd64] https://apt.releases.hashicorp.com {{ansible_distribution_release}} main
    become: yes

  - name: "Vault: install package"
    apt:
      name: 
      - vault
      state: latest
    become: yes
