- name: Link dotfiles
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "~/dotfiles/git/.gitconfig", dest: "~/.gitconfig"}
    - { src: "~/dotfiles/git/.gitignore_global", dest: "~/.gitignore_global"}