- name: "Install generic dev tools"
  apt: 
    name: ['direnv']
    state: latest
  become: yes

- name: "Install vscode"
  block:
  - name: Add microsoft GPG key
    apt_key: 
      url: https://packages.microsoft.com/keys/microsoft.asc
      keyring: /etc/apt/trusted.gpg.d/packages.microsoft.gpg
    become: yes

  - name: Add APT repository
    apt_repository:
      repo: deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main
    become: yes

  - name: Install code and supporting tools
    apt:
      name: ['apt-transport-https', 'code']
      state: latest
    become: yes

- name: Install SDKMAN
  block:
  - name: Verify if SDKMAN Is Installed
    stat:
      path: "~/.sdkman/"
    register: "sdkman_installed"

  - name: Install SDKMAN
    shell: 'curl -s http://get.sdkman.io | bash'
    args:
      executable: /bin/bash
      warn: no
    when: not sdkman_installed.stat.exists

  - name: Add SDKMAN in .zshrc
    lineinfile:
      dest: ~/.zshrc
      regexp: 'sdkman-init.sh'
      line: 'source $HOME/.sdkman/bin/sdkman-init.sh'
      state: present