- name: Install basic tools
  become: yes
  apt:
    state: latest
    name:
    - curl
    - jq
    - htop
    - mc
    - tmux
    - zip
    - sudo
    - bat
    - youtube-dl
    - screen
    - vim
    - pass
    - eog
    - tilda
    - kdeconnect

- name: Tilda config
  block:
  - name: Creates tilda config directory
    file:
      path: ~/.config/tilda
      state: directory
  - name: Link config file
    file:
      src: "~/dotfiles/tilda"
      dest: "~/.config/tilda/config_0"
      state: link
      force: yes
