- name: Basic tools ppas
  block:
  - name: Kernel mainline ppa
    apt_repository:
      repo: ppa:cappelikan/ppa
    become: yes

- name: Install basic tools
  become: yes
  apt:
    state: latest
    name:
    - curl
    - htop
    - mc
    - tmux
    - zip
    - p7zip-full
    - xz-utils
    - gawk
    - sudo
    - bat
    - youtube-dl
    - screen
    - vim
    - pass
    - eog
    - tilda
    - kdeconnect
    - mainline
    - net-tools
    - iputils-ping
    - iputils-tracepath
    - acpi
    - bluez
    - blueman
    - cups
    - pdftk
    - system-config-printer
    - pavucontrol
    - pulseaudio-module-bluetooth
    - firmware-sof-signed
    - imagemagick

## Airpods configuration
## https://askubuntu.com/questions/1408647/unable-to-pair-airpods-pro-with-ubuntu-22-04
##  ControllerMode = bredr in  /etc/bluetooth/main.conf
##  restart: sudo service bluetooth restart

- name: Install passff-host for password store
  block:
  - name: "passff-host: verify host is installed"
    stat:
      path: "~/.mozilla/native-messaging-hosts/passff.py"
    register: "passff_installed"

  - name: "passff-host: install"
    shell: curl -sSL github.com/passff/passff-host/releases/latest/download/install_host_app.sh | bash -s -- firefox    
    args:    
      warn: false
    when: not passff_installed.stat.exists

- name: Tilda config
  block:
  - name: "Tilda: creates config directory"
    file:
      path: ~/.config/tilda
      state: directory
  - name: "Tilda: link config file"
    file:
      src: "~/dotfiles/tilda"
      dest: "~/.config/tilda/config_0"
      state: link
      force: yes
