- name: Install basic tools
  become: yes
  apt:
    state: latest
    name:
    - curl
    - jq
    - htop
    - mc
    - tmux
    - zip
    - sudo
    - bat
    - youtube-dl
    - screen
    - vim
    - pass