- name: Basic tools ppas
  block:
  - name: Kernel mainline ppa
    apt_repository:
      repo: ppa:cappelikan/ppa
    become: yes

- name: Install basic tools
  become: yes
  apt:
    state: latest
    name:
    - curl
    - jq
    - htop
    - mc
    - tmux
    - zip
    - xz-utils
    - sudo
    - bat
    - xfce4-clipman-plugin
    - youtube-dl
    - screen
    - vim
    - pass
    - eog
    - tilda
    - kdeconnect
    - mainline
    - net-tools

- name: Install passff-host for password store
  block:
  - name: Verify if passff-host is installed
    stat:
      path: "~/.mozilla/native-messaging-hosts/passff.py"
    register: "passff_installed"

  - name: Install passff-host
    shell: curl -sSL github.com/passff/passff-host/releases/latest/download/install_host_app.sh | bash -s -- firefox    
    args:    
      warn: false
    when: not passff_installed.stat.exists

- name: Tilda config
  block:
  - name: Creates tilda config directory
    file:
      path: ~/.config/tilda
      state: directory
  - name: Link config file
    file:
      src: "~/dotfiles/tilda"
      dest: "~/.config/tilda/config_0"
      state: link
      force: yes
