- name: Install i3 tools
  become: yes
  apt:
    state: latest
    name:
    - i3
    - ranger
    - rofi
    - gnome-screenshot
    - flameshot
    - light
    
- name: Configure i3
  block:
  - name: Create config directories
    file: 
      path: "{{ item.path }}"
      state: directory
      mode: 0755
    loop: 
      - { path: "~/.config/dunst" }
      - { path: "~/.config/i3" }
  - name: Copy i3 scripts
    copy:
      src: "roles/i3/files/scripts"
      dest: "~/.config/i3/"
  - name: Download rofi-pass
    get_url:
      url: "https://raw.githubusercontent.com/carnager/rofi-pass/master/rofi-pass"
      dest: "~/.config/i3/scripts/rofi-pass"
  - name: Set scripts permissions
    file:
      path: "~/.config/i3/scripts"
      state: directory
      recurse: yes
      mode: 0755
  - name: Link i3 configurations
    file:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      state: link
      force: yes
    loop: 
      - { src: "~/dotfiles/i3/config", dest: "~/.config/i3/config"}
      - { src: "~/dotfiles/i3/rofipass.config", dest: "~/.config/rofi-pass/config"}
      - { src: "~/dotfiles/i3/i3status.conf", dest: "~/.i3status.conf"}
      - { src: "~/dotfiles/i3/Xresources", dest: "~/.Xresources"}
      - { src: "~/dotfiles/i3/dunstrc", dest: "~/.config/dunst/dunstrc"}

  - name: Configure lid events
    become: yes  
    copy:
      dest: "/etc/acpi/events/lm_lid"
      content: |
        event=button/lid.*
        action=/home/{{ansible_env.USER}}/.config/i3/scripts/lid
  - name: Battery notification
    become: yes
    copy:
      dest: "/etc/udev/rules.d/99-lowbat.rules"
      content: |
        SUBSYSTEM=="power_supply", ATTR{status}=="Discharging", ATTR{capacity}=="[0-15]", RUN+="/usr/bin/su {{ansible_env.USER}} -c /home/{{ansible_env.USER}}/.config/i3/scripts/battery_level"
