#!/usr/bin/env bash

# https://unix.stackexchange.com/questions/13746/how-can-i-detect-when-a-monitor-is-plugged-in-or-unplugged/60110#60110
# https://stackoverflow.com/questions/5469828/how-to-create-a-callback-for-monitor-plugged-on-an-intel-graphics

SCR_EXT="DP-1"
SCR_INT="eDP-1"

screen_mirror() {
  xrandr --output $SCR_INT --auto --scale 2x2 --output $SCR_EXT
}

screen_join() {
  xrandr --output $SCR_INT --auto --brightness 0.65 --left-of $SCR_EXT --output $SCR_EXT --primary --auto 
}

screen_external() {
  xrandr --output $SCR_INT --off --output $SCR_EXT --auto --scale 1x1
}

screen_internal() {
  xrandr --output $SCR_INT --auto --scale 2x2 --brightness 0.65 --output $SCR_EXT --off 
}

main() {
  case "$1" in
    "external")
    screen_external
    ;;
    "internal" | "built-in")
    screen_internal
    ;;
    "mirror")
    screen_mirror
    ;;
    "join")
    screen_join
    ;;
    *)
    echo "Unknown action \"$1\"" 1>&2
    exit 1
    ;;
  esac
}

if [ $# -ne 1 ]; then
  echo "Usage: screens {internal|external|mirror|join}"
  exit 1
fi

main $@